### ISSUE TITLE
Won't toggle

### ISSUE THREAD

**Issue by juanlatorre** [sconxu/react-native-checkbox#56] opened 2017-03-30 22:15 UTC
Hi, I copied the code on the README, but the toggle doesn't change the image and there's an annoying  white background.

![issue 1](https://cloud.githubusercontent.com/assets/4494526/24528515/2c786160-157d-11e7-94c3-52863acbbb19.gif)

Thanks.

**Comment by androhong** [comment] 2017-04-10 08:43
After remove below code, the check box is changed. But init value doesn't worked. 

  checked={true}

**Comment by omarkhaled11** [comment] 2017-05-06 14:16
initial value with checked prop breaks toggling completely

**Comment by Laurensdc** [comment] 2017-11-06 12:24
I'm having the same problem. When setting the `checked` prop, the `onChange` always returns a fixed value.

**Comment by fr3em1nd** [comment] 2017-11-22 12:41
You guys just need to put a default value:

 value={true}

ex:
  <CheckBox
   label='Label'

 value={true}

 onChange={(value) => {
       console.log(value)
      }}


 />

**Comment by maxhis** [comment] 2018-01-30 08:52
Same problem here, do you guys make toggle working with an initial value?

**Comment by RicardoAlmeida25** [comment] 2018-02-12 15:48
@maxhis Try using an initial value with the prop **value** and remove the **checked** option. It worked for me.

**Comment by adrianboimvaser** [comment] 2018-03-05 20:32
@RicardoAlmeida25 the `value` prop doesn't exist.

**Comment by adrianboimvaser** [comment] 2018-03-05 20:34
To make it work just negate the argument from `onChange`:
```
<CheckBox
  label="Some label"
  checked={this.props.checked}
  onChange={(checked) => this.props.toggleMyTicketsFirst(!checked)}/>
```

**Comment by b8ne** [comment] 2018-03-25 00:03
The issue is here
```
onChange() {
        if (this.props.onChange &&  typeof this.props.checked === 'boolean') {
            this.props.onChange(this.props.checked);
        } else {
            let internalChecked = this.state.internalChecked;
            let newState = !internalChecked;

            if(this.props.onChange){
              this.props.onChange(newState);
            }
            this.setState({
                internalChecked: newState
            });
        }
    }
```
If the `checked` prop is present, it is returned, so the value never changes.
The negation should be here, not in user code.
ie.
```
onChange() {
        if (this.props.onChange &&  typeof this.props.checked === 'boolean') {
            this.props.onChange(!this.props.checked); // <=== Negate the prop value
        } else {
            let internalChecked = this.state.internalChecked;
            let newState = !internalChecked;

            if(this.props.onChange){
              this.props.onChange(newState);
            }
            this.setState({
                internalChecked: newState
            });
        }
    }
```

**Comment by baurine** [comment] 2018-03-28 10:03
@b8ne this is the reason, it totally can't work now, thank you so much!

**Comment by b8ne** [comment] 2018-03-28 21:56
Just added #75 @sconxu so if you agree, merge when ready :)

**Comment by sconxu** [comment] 2018-04-02 18:25
Merged

**Closed by sconxu** 2018-04-02 18:25 UTC
